### ISSUE TITLE
Remove subscribers count

### ISSUE THREAD

**Issue by quietlemon** [breadtubetv/breadtubetv#100]
The number of subscribers should in my opinion be hidden from the HTML output. It's an irrelevant information that can easily be faked. It does not help to evaluate a content's value (more popular does not necessarily mean more interesting) but helps foster competition between vidcasters and their respective communities.

I believe displaying the number of subscribers (or using it as a sorting parameter) only provides incentives for creating/buying fake subscribers. As an anarchist platform, i believe breadtube.tv should take a stand against subscribers count as a meaningful metrics.

Time-based ordering and community rating of individual pieces of content are in my view way more valuable to end-users like me :)

**Comment by dirkkelly** [comment]
This is a great point, sorry for my late reply I guess I don't get email notifications for this channel. Am currently dealing with an issue of subscriber count for sorting, I'll change this to sorting on slug alphabetically and we'll take it from there.

**Comment by jaymickey** [comment]
Given we've switch the ordering of content to be alphabetical rather than by subscriber count, can this issue be closed? There has been some discussion about this on discord, and I agree that subscriber count is currently our only way of tracking the dissemination of these ideas.

It's quite possible we can and/or will look into better way to do this in the future, but that could be a separate issue.

**Comment by craiglonsdale** [comment]
I agree I think we should close this for now. Maybe we can find a better way to group things later or generate 'heat maps' based on how often they are updated or accessed. Don't know, but it can't stay alphabetical forever.
